name: pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: mkdir public
    - run: mv dist/* public
    - run: gzip -k -9 $(find public -type f -not -name "*.jpg" -not -name "*.png")

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages